config/routes.rb
Rails.application.routes.draw do
  resources :installments
  resources :users
  root 'users#index'

end

app/models/installment.rb
class Installment < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :installments, :foreign_key => :user_id, dependent: :destroy
	validates_presence_of :name, :email, :total_amount
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/installments_controller.rb
class InstallmentsController < ApplicationController
  before_action :set_installment, only: [:show, :edit, :update, :destroy]

  # GET /installments
  # GET /installments.json
  def index
    @installments = Installment.all
  end

  # GET /installments/1
  # GET /installments/1.json
  def show
  end

  # GET /installments/new
  def new
    @installment = Installment.new
    @installment.user_id = params[:user_id]
  end

  # GET /installments/1/edit
  def edit
  end

  # POST /installments
  # POST /installments.json
  def create
    @installment = Installment.new(installment_params)

    respond_to do |format|
      if @installment.save
        update_user(@installment.user)
        format.html { redirect_to @installment, notice: 'Installment was successfully created.' }
        format.json { render :show, status: :created, location: @installment }
      else
        format.html { render :new }
        format.json { render json: @installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /installments/1
  # PATCH/PUT /installments/1.json
  def update
    respond_to do |format|
      if @installment.update(installment_params)
        format.html { redirect_to @installment, notice: 'Installment was successfully updated.' }
        format.json { render :show, status: :ok, location: @installment }
      else
        format.html { render :edit }
        format.json { render json: @installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /installments/1
  # DELETE /installments/1.json
  def destroy
    @user = @installment.user
    @installment.destroy
    update_user(@user)
    respond_to do |format|
      format.html { redirect_to user_url(@user), notice: 'Installment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_installment
      @installment = Installment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def installment_params
      params.require(:installment).permit(:due_date, :payment_date, :status, :amount, :user_id)
    end

    def update_user(user)
      user.update_attributes(:emi_option => user.installments.count)
    end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        if params[:user][:auto_generate] == "1"
          create_installments(@user)
        end
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        update_installments(@user)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :total_amount, :discount, :percentage, :emi_option)
    end

    def create_installments(user)
      if user.discount
        net_amount=user.total_amount-user.percentage
      else
        net_amount=user.total_amount
      end
      monthly_amount=net_amount/user.emi_option
      # Installment.create(:due_date=>Date.today, :payment_date=>Date.today, :status=>"paid",:amount=>monthly_amount,:user_id=>user.id)
        d= Date.today
      for i in 1..(user.emi_option)
        Installment.create(:due_date=>d, :status=>"scheduled",:amount=>monthly_amount,:user_id=>user.id)
        d=d+(12/user.emi_option).months
      end
    end

    def update_installments(user)
      old_amount = user.installments.sum(:amount)
      difference = user.total_amount - old_amount - user.percentage
      if difference != 0
        remaining_installments = user.installments.where("status != ?", 'paid')
        ri_count = remaining_installments.count
        if ri_count == 0
          Installment.create(:due_date => Date.today, :status => "scheduled", :amount => difference, :user_id => user.id)
          user.update_attributes(:emi_option => user.emi_option + 1)
        else
          remaining_installments.each do |inst|
            inst.update_attributes(:amount => inst.amount + difference/ri_count.to_f)
          end
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/installments_helper.rb
module InstallmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/installments/_form.html.erb
<%= form_for(@installment) do |f| %>
  <% if @installment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@installment.errors.count, "error") %> prohibited this installment from being saved:</h2>

      <ul>
      <% @installment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :payment_date %><br>
    <%= f.date_select :payment_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.radio_button :status,"paid"%>Paid
    <%= f.radio_button :status,"scheduled"%>Scheduled
    <%= f.radio_button :status,"over_due"%>Over Due
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <%= f.hidden_field :user_id, :value => @installment.user_id  %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/installments/edit.html.erb
<h1>Editing Installment</h1>

<%= render 'form' %>

app/views/installments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Installments</h1>

<table>
  <thead>
    <tr>
      <th>Due date</th>
      <th>Payment date</th>
      <th>Status</th>
      <th>Amount</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @installments.each do |installment| %>
      <tr>
        <td><%= installment.due_date %></td>
        <td><%= installment.payment_date %></td>
        <td><%= installment.status %></td>
        <td><%= installment.amount %></td>
        
        <td><%= link_to 'Show', installment %></td>
        <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
        <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Installment', new_installment_path, :method => "get" %>

app/views/installments/new.html.erb
<h1>New Installment</h1>

<%= render 'form' %>

app/views/installments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Due date:</strong>
  <%= @installment.due_date %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @installment.payment_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @installment.status %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @installment.amount %>
</p>


<%= button_to 'Edit', edit_installment_path(@installment), :method => "get" %>
<br> <br>
<%= button_to 'Back to User', user_path(@installment.user), :method => "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Furniture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.number_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.radio_button :discount,"true"%>Yes
    <%= f.radio_button :discount,"false", :checked => true%>No
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :percentage %>
  </div>

  <div class="field">
    <%= f.check_box :auto_generate, :checked => true %> Automatically generate installments
  </div>
  
  <div class="field">
    <%= f.label :installments %><br>
    <%= f.number_field :emi_option ,"min"=>1,"max"=>12%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<% if @users.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Total amount</th>
        <th>Discount</th>
        <th>Discount Amount</th>
        <th>Installments</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.total_amount %></td>
          <td><%= user.discount %></td>
          <td><%= user.percentage %></td>
          <td><%= user.emi_option %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br>

<%= button_to 'Add New User', new_user_path, :method => "get" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>


 <script type="text/javascript">
	$(document).ready(function(){
        $("#user_auto_generate").on('change', function(){
            $("#user_emi_option").prop('disabled', !($("#user_auto_generate").val() == "1"));
        });

});
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @user.total_amount %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @user.discount %>
</p>

<% if @user.discount %>
  <p>
    <strong>Discount Amount:</strong>
    <%= @user.percentage %>
  </p>
<% end %>

<% if @user.emi_option.present? %>
  <p>
    <strong>Number of Installments:</strong>
    <%= @user.emi_option %>
  </p>
<% end %>

<%= button_to 'Edit User', edit_user_path(@user), :method => "get" %>
<br><br>

<%@installments = @user.installments%>

<% if @installments.count > 0 %>

  <h1>Listing Installments</h1>

  <table>
    <thead>
      <tr>
        <th>Due date</th>
        <th>Payment date</th>
        <th>Status</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @installments.each do |installment| %>
        <tr>
          <td><%= installment.due_date %></td>
          <td><%= installment.payment_date %></td>
          <td><%= installment.status %></td>
          <td><%= installment.amount %></td>
          <% if installment.status.downcase != 'paid' %>
            <td><%= link_to 'Edit', edit_installment_path(installment) %></td>
            <td><%= link_to 'Destroy', installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>
<br>

<%= button_to 'Add Installment', new_installment_path, :method => "get", :params => {:user_id => @user.id} %>